CREATE OR REPLACE PACKAGE ESHOP_REPORT_API AS

PROCEDURE SP_MONTHLYSALES
(
    RP_MONTH IN INT,
    RP_YEAR IN INT,
    RP_CURSOR OUT SYS_REFCURSOR
);

END ESHOP_REPORT_API;
/

CREATE OR REPLACE PACKAGE BODY ESHOP_REPORT_API AS

PROCEDURE SP_MONTHLYSALES
(
    RP_MONTH IN INT,
    RP_YEAR IN INT,
    RP_CURSOR OUT SYS_REFCURSOR
)
AS 
BEGIN 
OPEN RP_CURSOR FOR
SELECT EXTRACT(DAY FROM CREATED_AT) AS DAY, COUNT(*) AS ORDERS_COUNT, SUM(TOTAL) AS REVENUE FROM ORDERS
WHERE EXTRACT(MONTH FROM CREATED_AT) = RP_MONTH AND EXTRACT(YEAR FROM CREATED_AT) = RP_YEAR
GROUP BY EXTRACT(DAY FROM CREATED_AT);
END;

END ESHOP_REPORT_API;
/
